[package]
name = "moonshot"
version = "0.1.0"
authors = ["Quentin Kniep <hello@quentinkniep.com>"]
edition = "2018"

[dependencies]
amethyst = { version = "0.15", features = ["metal"] }
amethyst_rendy = "0.15"
log = "0.4"
serde = "1"
